language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests # or py.test for Python versions 3.5 and below

after_success:
  - coveralls
